<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">myCustomJ</value>
  <value name="encodeutf8">true</value>
  <value name="body">DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCglTdHJpbmcJQnV5ZXJJZGVudGl0eSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBp
cGVsaW5lQ3Vyc29yLCAiQnV5ZXJJZGVudGl0eSIgKTsNCg0KaWYgKCJGb3giLmVxdWFsc0lnbm9y
ZUNhc2UoQnV5ZXJJZGVudGl0eSkpIHsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwg
IkJ1eWVySWRlbnRpdHkiLCBCdXllcklkZW50aXR5LnRvVXBwZXJDYXNlKCkgKyAiIElORFVTVFJJ
RVMiICk7DQp9IGVsc2Ugew0KCVN0cmluZyBFcnJvck1zZyA9ICJJbnZhbGlkIEJ1eWVyOiAiICsg
QnV5ZXJJZGVudGl0eTsNCglJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgIkVycm9yTXNn
IiwgRXJyb3JNc2cgKTsNCn0NCg0KcGlwZWxpbmVDdXJzb3IuZGVzdHJveSgpOw0K</value>
</Values>
