    @echo off
    set WM_TOP=C:\webmethods7
    set IS_TOP=%WM_TOP%\IntegrationServer
    set CMN_LIB=%WM_TOP%\common\lib
    
    set PKG=%IS_TOP%\packages\AdvTrainingISDemo

    set CLASSPATH=%CLASSPATH%;%WM_TOP%\lib\wm-isclient.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\updates\IS_7-1-2-0.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\updates\TNS_7-1-2-0.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\classes\
    set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\wm-isserver.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-isclient.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-wsclient.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-brokerclient.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-client.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-jmsclient.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jms.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\icu4j.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-scg-cluster.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-scg-core.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-scg-jdbcpool.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-scg-security.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-g11nutils.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\glue.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-mapi.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-lwq.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-fabric-agent.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\activation.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\wsdl4j.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\coherence.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\coherence-login.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\derby.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\enttoolkit.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxen-core.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jboss-common.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jnpserver.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\log4j.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\mail.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\saxpath.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\xmlsec.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-beanutils.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-collections.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-digester.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-logging.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\common\agent\wss4j-1.5.1.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-logging.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\sl53_cj36.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\tangosol.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\xalan.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\opensaml.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\saaj-api.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-directory.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-directory-components.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-mws-library.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-server.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-schemas.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-common.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-jsf.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-caf-jsf-mws.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-calendar-components.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\axis.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\javax.servlet.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\ldap.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\ldapbp.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\ldapfilt.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\ldapjdk.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\portlet-api.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxb-api.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxb-impl.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxb-libs.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxrpc-api.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\relaxngDataType.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\xsdlib.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxen-dom.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-discovery.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-calendar.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\ical4j.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\commons-lang.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\xercesImpl.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\common\conf\
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\jars\jakarta-oro-2.0.5.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\jars\nfjava.zip
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\jars\sqljdbc.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\jars\wmjmsnaming.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmART\code\jars\static\wmartbundle.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmEDIINT\code\jars\static\ediint.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmFlatFile\code\jars\static\ffcore.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmJDBCAdapter\code\jars\static\javaxsql.zip
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmMonitor\code\jars\static\mIcons.zip
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmPKI\code\classes\
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmPRT\code\jars\static\wmprt.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmTN\code\jars\static\tncore.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmWin32\code\classes\
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\WmXSLT\code\jars\static\wmxslt.jar
rem set CLASSPATH=%CLASSPATH%;.\
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\wmbrokerclient.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\g11nutils.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\jms.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\wmjmsclient.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\jta.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\Broker\lib\wmjmsnaming.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\wm-isclient.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\mail.jar
rem set CLASSPATH=%CLASSPATH%;%CMN_LIB%\ext\jaxrpc-api.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\jvm\win150\jre\lib\rt.jar
rem set CLASSPATH=%CLASSPATH%;C:\webMethods7\jvm\win150\jre\lib\i18n.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\lib\wm-isproxy.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\..\common\lib\wm-converters.jar
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\config\Caching
rem set CLASSPATH=%CLASSPATH%;%IS_TOP%\packages\AdvTrainingISDemo\code\classes
    
    javac -g -classpath %CLASSPATH% -sourcepath %PKG%\code\source -d %PKG%\code\classes %PKG%\code\source\advTrainingISDemo\demo\errorHandling.java